# stats available at
# https://ci.appveyor.com/project/strukturag/libde265
image: Visual Studio 2019
configuration: Release

matrix:
  allow_failures:
    - arch: arm64

environment:
  matrix:
  - arch: x64
  - arch: arm64

install:
  - git clone --depth 1 https://github.com/strukturag/libde265-data.git

before_build:
  - mkdir build
  - cd build
  - cmake .. -A %arch%

build:
  verbosity: normal

for:
  -
    matrix:
      only:
        - arch: x64
    before_test:
      - copy /y dec265\Release\dec265.exe .
      - copy /y enc265\Release\enc265.exe .
      - copy /y libde265\Release\libde265.dll .
    test_script:
      - dec265.exe -q -c -f 100 ..\libde265-data\IDR-only\paris-352x288-intra.bin
      - dec265.exe -t 4 -q -c -f 100 ..\libde265-data\IDR-only\paris-352x288-intra.bin
      - dec265.exe -q -c -f 100 ..\libde265-data\RandomAccess\paris-ra-wpp.bin
      - dec265.exe -t 4 -q -c -f 100 ..\libde265-data\RandomAccess\paris-ra-wpp.bin

artifacts:
  - path: build
  - path: build\**\Release\*.exe
  - path: build\**\Release\*.dll
